/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package form;

import common.functionCommon;
import java.awt.Color;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.ResultSet;
import java.sql.Statement;
import javax.swing.UIManager;

/**
 *
 * @author ade
 */
public class loginForm extends javax.swing.JFrame {

    /**
     * Creates new form loginForm
     */
    public loginForm() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panelLogin1 = new panelLayout.panelLogin();
        txEmail = new javax.swing.JTextField();
        txPassword = new javax.swing.JPasswordField();
        jButton1 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DO_NOTHING_ON_CLOSE);
        setTitle("Login to project management and inventory");
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosing(java.awt.event.WindowEvent evt) {
                formWindowClosing(evt);
            }
        });
        addComponentListener(new java.awt.event.ComponentAdapter() {
            public void componentResized(java.awt.event.ComponentEvent evt) {
                formComponentResized(evt);
            }
        });
        getContentPane().setLayout(null);

        panelLogin1.setLayout(null);

        txEmail.setToolTipText("Insert Username or Email");
        txEmail.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                txEmailFocusGained(evt);
            }
        });
        txEmail.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txEmailKeyReleased(evt);
            }
        });
        panelLogin1.add(txEmail);
        txEmail.setBounds(410, 360, 270, 30);

        txPassword.setToolTipText("Insert Password");
        txPassword.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                txPasswordFocusGained(evt);
            }
        });
        txPassword.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txPasswordKeyReleased(evt);
            }
        });
        panelLogin1.add(txPassword);
        txPassword.setBounds(410, 410, 270, 30);

        jButton1.setBackground(new java.awt.Color(204, 204, 204));
        jButton1.setFont(new java.awt.Font("Dialog", 0, 12)); // NOI18N
        jButton1.setForeground(new java.awt.Color(0, 0, 0));
        jButton1.setText("Login");
        jButton1.setBorder(null);
        jButton1.setBorderPainted(false);
        jButton1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButton1.setDefaultCapable(false);
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        panelLogin1.add(jButton1);
        jButton1.setBounds(330, 500, 110, 30);

        getContentPane().add(panelLogin1);
        panelLogin1.setBounds(0, 0, 1020, 760);

        java.awt.Dimension screenSize = java.awt.Toolkit.getDefaultToolkit().getScreenSize();
        setBounds((screenSize.width-1029)/2, (screenSize.height-799)/2, 1029, 799);
    }// </editor-fold>//GEN-END:initComponents

    private void formWindowClosing(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowClosing
        if (javax.swing.JOptionPane.showConfirmDialog(null, "Are you sure to Exit?", "Question",
                javax.swing.JOptionPane.YES_NO_OPTION,
                javax.swing.JOptionPane.QUESTION_MESSAGE) == javax.swing.JOptionPane.YES_OPTION) {
            System.exit(0);
        }
    }//GEN-LAST:event_formWindowClosing

    private void txEmailFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txEmailFocusGained
        txEmail.selectAll();
    }//GEN-LAST:event_txEmailFocusGained

    private void txPasswordFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txPasswordFocusGained
        txPassword.selectAll();
    }//GEN-LAST:event_txPasswordFocusGained

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        String EnkripPAssword = new String(txPassword.getPassword());
        if (txEmail.getText().length() < 1) {
            txEmail.requestFocus();
            javax.swing.JOptionPane.showConfirmDialog(null, "Please Insert Username or Email", "Information",
                    javax.swing.JOptionPane.PLAIN_MESSAGE);
        } else if (EnkripPAssword.length() < 1) {
            txPassword.requestFocus();
            javax.swing.JOptionPane.showConfirmDialog(null, "Please Insert Password", "Information",
                    javax.swing.JOptionPane.PLAIN_MESSAGE);
        } else {

            functionCommon fc = new functionCommon();
            try {
                Connection cn = DriverManager.getConnection(fc.connection, fc.userName, fc.passWord);

                EnkripPAssword = fc.MD5(EnkripPAssword);
                Statement st = cn.createStatement();
                String sql = "select id,roles_id,first_name,last_name from user where ("
                        + "username='" + txEmail.getText() + "' "
                        + " or email='" + txEmail.getText() + "') "
                        + "and password = '" + EnkripPAssword + "'";
                ResultSet rs = st.executeQuery(sql);
                if (rs.next()) {
                    formMenu fm = new formMenu();
                    fm.setVisible(true);
                    fm.userID = rs.getInt("id");
                    fm.role_id = rs.getInt("roles_id");
                    fm.lbFirstname.setText(rs.getString("first_name") + " " + rs.getString("last_name"));
                    dispose();
                } else {
                    javax.swing.JOptionPane.showConfirmDialog(null, "Wrong Email/User Name or PAssword", "Warning",
                            javax.swing.JOptionPane.PLAIN_MESSAGE);
                }
                st.close();
                cn.close();
            } catch (Exception ex) {
                if (fc.isDebugging) {
                    System.out.println(" error in jButton1ActionPerformed " + ex.getMessage());
                }
            }
        }
    }//GEN-LAST:event_jButton1ActionPerformed

    private void txEmailKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txEmailKeyReleased
        if (evt.getKeyCode() == evt.VK_ENTER) {
            txPassword.requestFocus();
        }
    }//GEN-LAST:event_txEmailKeyReleased

    private void txPasswordKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txPasswordKeyReleased
        if (evt.getKeyCode() == evt.VK_ENTER) {
            jButton1ActionPerformed(null);
        }
    }//GEN-LAST:event_txPasswordKeyReleased

    private void formComponentResized(java.awt.event.ComponentEvent evt) {//GEN-FIRST:event_formComponentResized
        int Xposition = 0;
     if (getWidth()-10>panelLogin1.getWidth())
        Xposition=(getWidth()-10-panelLogin1.getWidth())/2;
     int Yposition = 0;
     if (getHeight()-10>panelLogin1.getHeight())
        Yposition=(getHeight()-panelLogin1.getHeight())/2;
     panelLogin1.setLocation(Xposition, Yposition);
    }//GEN-LAST:event_formComponentResized

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        
        UIManager.put("ComboBox.selectionBackground", Color.GRAY);
        UIManager.put("ComboBox.selectionForeground", Color.WHITE);
        
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Metal".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(loginForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(loginForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(loginForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(loginForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new loginForm().setVisible(true);
            }
        });
    }
    
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private panelLayout.panelLogin panelLogin1;
    private javax.swing.JTextField txEmail;
    private javax.swing.JPasswordField txPassword;
    // End of variables declaration//GEN-END:variables
 
}
